name: build package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      workdir:
        required: true
        type: string

      # optional variables
      image_name:
        required: false
        type: string
        default: ${{ github.repository }}
      registry: 
        required: false
        type: string
        default: ghcr.io
      username:
        required: false
        type: string
        default: ${{ github.actor }}
      dockerfile:
        required: false
        type: string
        default: Dockerfile
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install cosign
        uses: sigstore/cosign-installer@v1.4.1
      - name: Check install!
        run: cosign version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}/${{ inputs.package }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          registry: ${{ inputs.registry }}
          context: ./${{ inputs.workdir }}
          file: ./${{ inputs.workdir }}/${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
            

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ inputs.registry }}/${{ inputs.image_name }}/${{ inputs.package }}@${{ steps.build-and-push.outputs.digest }}
