name: ci

on:
  push:
    branches:
      - 'dev'
  # tags:        
  #     - v* #v1.0.0

jobs:
    build_ds_opal:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_opal
        tags: 
        image_name: env.IMAGE_NAME

    build_ds_poll:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_poll
        tags: 
        image_name: env.IMAGE_NAME

    build_ds_queue:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_queue
        tags: 
        image_name: env.IMAGE_NAME

    build_ds_simple_client:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_simple_client
        tags: 
        image_name: env.IMAGE_NAME

    build_ds_test:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_test
        tags: 
        image_name: env.IMAGE_NAME

